In [4]:
import pandas as pd
from sqlalchemy import create_engine
import matplotlib.pyplot as plt
import numpy as np

In [5]:
# database_path = 'postgresql://postgres:postgres@localhost/Employees'
# engine = create_engine("sqlite:///{database_path}")
# conn = engine.connect()

engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost/mls_db')
connection = engine.connect()

In [64]:
summary = pd.read_sql('SELECT * FROM club_summary_stats_v2', connection)
summary

,club_id,club,Goals_For,Goals_Against,Min Salary,Mean Salary,Max Salary,Roster Payroll,Wins (%)
0,23.0,Toronto FC,57.0,52.0,56250.00,758345.82,6500000.00,24267066.18,0.456
1,9.0,LA Galaxy,58.0,59.0,56250.00,654565.99,7200000.00,19636979.69,0.492
2,2.0,Chicago Fire,55.0,47.0,56250.00,611249.32,5600000.04,17114980.99,0.357
3,10.0,LAFC,85.0,37.0,56250.00,509998.20,6300000.00,13769951.28,0.712
4,21.0,Seattle Sounders FC,52.0,49.0,57225.00,488514.80,2502500.04,13678414.29,0.533
5,12.0,Montreal Impact,47.0,60.0,56250.00,438409.12,4443333.37,13152273.71,0.381
6,1.0,Atlanta United,58.0,43.0,56250.00,404909.97,3058333.33,12957118.93,0.563
7,16.0,Orlando City SC,44.0,52.0,56250.00,419107.54,2486249.70,12573226.29,0.310
8,18.0,Portland Timbers,52.0,49.0,56250.00,464959.87,2853341.33,12553916.46,0.459
9,22.0,Sporting Kansas City,49.0,67.0,56250.00,416230.19,1649999.96,12070675.60,0.333
10,19.0,Real Salt Lake,46.0,41.0,56250.00,358638.34,2001666.67,11117788.60,0.508
11,11.0,Minnesota United,52.0,43.0,56250.00,379731.63,1750000.08,10632485.61,0.500
12,20.0,San Jose Earthquakes,52.0,55.0,57225.00,342580.01,1604042.36,10619980.43,0.413
13,4.0,Columbus Crew,39.0,47.0,56250.00,366021.15,1471666.64,10614613.28,0.333
14,13.0,New England Revolution,50.0,57.0,56250.00,408008.36,2337500.00,10608217.28,0.393
15,14.0,New York City FC,63.0,42.0,56250.00,371985.24,2000000.04,10415586.82,0.621
16,5.0,DC United,42.0,38.0,56250.00,377602.86,3507500.04,10195277.26,0.456
17,17.0,Philadelphia Union,58.0,50.0,56250.00,339818.56,2274087.24,9854738.30,0.525
18,6.0,FC Cincinnati,31.0,75.0,56250.00,289845.88,1965008.00,9564914.01,0.194
19,7.0,FC Dallas,54.0,46.0,70250.04,284107.07,870000.08,8807319.09,0.441
20,8.0,Houston Dynamo,49.0,59.0,56250.00,301546.53,1245049.96,8744849.28,0.375
21,15.0,New York Red Bulls,53.0,51.0,56250.00,298928.75,1380000.00,8668933.79,0.452
22,3.0,Colorado Rapids,58.0,63.0,57225.00,307142.66,2475000.04,8599994.41,0.387
23,24.0,Vancouver Whitecaps,37.0,59.0,56250.00,271737.66,1277499.90,8152129.65,0.276

In [65]:
pwd

'C:\\Users\\a_mcr\\Desktop\\Bootcamp\\Homeworks\\ETL-Challenge\\mls-data-asmvm'

In [66]:
summary.to_csv('../data/processed/summary_table.csv', encoding='utf-8')